import { Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";
import { Explain } from "@/components/ui/tooltip";

/**
 * Minimal marker for anything derived or generated by this application — theme
 * detection, sentiment grouping, generated summaries, suggested wording — as
 * opposed to a verbatim source value. Rendered as a single quiet icon; the
 * explanation lives in the tooltip. Verbatim data never carries this marker.
 */
export function AiTag({
  kind = "derived",
  className,
}: {
  /** `derived` = classified/aggregated from source data; `generated` = wording written by the app. */
  kind?: "derived" | "generated";
  className?: string;
}) {
  const explanation =
    kind === "generated"
      ? "AI-assisted wording generated by this application from the underlying source data. It is not a quotation and should be reviewed before external use."
      : "AI-assisted classification derived by this application from the source data (for example theme or sentiment detection). The underlying reviews and specifications are shown verbatim; only this grouping is machine-derived.";

  return (
    <Explain content={explanation}>
      <span
        tabIndex={0}
        aria-label={kind === "generated" ? "AI-generated wording" : "AI-derived classification"}
        className={cn(
          "inline-flex shrink-0 cursor-help items-center align-middle text-daikin-400 transition-colors hover:text-daikin-600 focus-visible:text-daikin-600",
          className,
        )}
      >
        <Sparkles className="size-3.5" strokeWidth={2.25} aria-hidden />
      </span>
    </Explain>
  );
}
